apiVersion: v1
kind: Service
metadata:
  name: bgpalerter-comcast
  namespace: bgpalerter-comcast
  labels:
    k8s-app: bgpalerter
spec:
  ports:
  - port: 8011
    targetPort: 8011
    protocol: TCP
    name: bgpalerter-tcp
  type: ClusterIP
  selector:
    app: bgpalerter